#backend/src/utlis/mongo_db/conexion.py
from pymongo import MongoClient
# from pymongo.errors import ConnectionFailure

def connect_to_mongodb():
    try:
        uri = "mongodb://localhost:27017"
        client = MongoClient(uri, serverSelectionTimeoutMS=5000)  # Timeout para evitar bloqueos
        # Verificar la conexi칩n
        client.admin.command({'ping': 1})  # Prueba si el servidor est치 vivo
        print("Conexi칩n a MongoDB exitosa al crear LOL")
        
        database = client["LOL"]  # Nombre de la base de datos
        collection = database["champions"]  # Nombre de la colecci칩n
        return database, collection
    
    except Exception as e:
        raise Exception(
            "The following error occurred: ", e)
